### ISSUE TITLE
llama 13b version?

### ISSUE THREAD

**Issue by guyuchao** [ali-vilab/Ranni#2]
The paper mentioned you use llama-13B as the LLM model. But the provided version is 7B. Have you observed any performance drop because of the different LLM size. Will you plan to release the 13B version?

**Comment by thss15fyt** [comment]
We release the 7B version for more efficient running of the demo. The 13B version shows slightly better performance on condition generation. We are also planning to release more checkpoints (both LLM and diffusion) after the completion of basic code.

---- Replied Message ----
| From | Yuchao ***@***.***> |
| Date | 04/08/2024 22:14 |
| To | ali-vilab/Ranni ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [ali-vilab/Ranni] llama 13b version? (Issue #2) |

The paper mentioned you use llama-13B as the LLM model. But the provided version is 7B. Have you observed any performance drop because of the different LLM size. Will you plan to release the 13B version?
